import type { MetadataRoute } from "next";

/**
 * Web App Manifest for the Convey PWA.
 *
 * Installability rules: standalone display, a 192 and a 512 PNG icon, and a
 * monochrome theme (white background, black theme color) matching the
 * product's black-and-white language. Icons are derived from the standalone
 * Convey mark under `public/brand/convey-mark.png`, generated by
 * `scripts/generate-convey-icons.py`.
 *
 * Icons: the 192 and 512 PNGs are plain "any" purpose (safe zone is the full
 * canvas). A separate 512 maskable PNG (`convey-maskable-512.png`) carries the
 * same mark scaled so its corners sit inside the central 80% safe-zone circle
 * on a full-bleed white background, so Android adaptive-icon shaping never
 * crops the mark. It is declared with `purpose: "maskable"` only.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Convey",
    short_name: "Convey",
    description:
      "Convey turns natural language into enforceable Sui agreements, independent verification, QR payments, and guarded treasury actions.",
    id: "/app",
    start_url: "/app",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: "#000000",
    icons: [
      {
        src: "/icons/convey-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/convey-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/convey-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    shortcuts: [
      {
        name: "Ask Convey",
        short_name: "Assistant",
        description: "Describe a payment, agreement, split, or treasury outcome",
        url: "/app",
      },
      {
        name: "Verify a claim",
        short_name: "Verify",
        description: "Run two independent Gonka reviews and inspect the request trail",
        url: "/verify",
      },
      {
        name: "Scan or show QR",
        short_name: "Scan",
        description: "Pay, collect, split, or carry a request between devices",
        url: "/qr-ferry",
      },
    ],
  };
}
